gestion_cursos_posgrado/apps/urls.py
from django.db.models import Index
from django.urls import path

from apps import views

urlpatterns =[
    path('index/', views.index, name = 'index'),
    path('index/<int:pk>/', views.inscribirPersonsaCurso, name='inscribirPersonsaCurso'),
    path('darDeBajaCursoPersona/<int:pk>', views.darDeBajaPersonsaCurso, name='darDeBajaCursoPersona'),
    path('abonarCurso/<int:pk>/', views.registrarAbonado, name='abonarCurso'),

    path('reciboDePago/<int:pk>,<str:pkC>/',views.reciboDePago, name='reciboDePago'),

    path('index/inicioSesion/', views.inicioSesion, name = 'inicioSesion'),

    path('administracionInscripcion/', views.administracionInscripcion, name='administracionInscripcion'),
    path('index/<int:pk>/nuevaInscripcion/', views.crearPersona, name='nuevaInscripcion'),
    path('editarInscripcion/<int:pk>',views.editarPersona, name='editarInscripcion'),
    path('eliminarInscripcion/<int:pk>',views.borrar_persona, name='eliminarInscripcion'),

    path('registroDocenteAlumno/', views.registroDocenteAlumno, name='registroDocenteAlumno'),

    # path('inscripcion/', views.crearPersona, name='inscripcionAlCurso'),
    # path('inscripcionAlCurso/', views.inscripcionAlCurso, name='inscripcionAlCurso'),
    #path('index/<int:pk>/inscripcionAlCurso', views.inscripcionAlCurso, name='inscripcionAlCurso'),

    path('administracionDeCursos/', views.paginaDelAdmin, name='administracionDeCursos'),
    #path('administracionDeCursos/creacionDeCurso', views.creacionDeCursos, name='creacionDeCurso'),
    path('administracionDeCursos/cursosDisponibles', views.cursosRegistrados, name='cursosDisponibles'),
    #path('administracionDeCursos/resolucion', views.nuevaResolucion, name='resolucion'),

    path('administracionDeCursos/estadisticas', views.pagEstadisticas, name='estadisticas'),
    path('administracionDeCursos/estadisticas/estadisticasFiltradas', views.pagEstadisticasFiltradas, name='estadisticasFiltradas'),

    path('administracionDeCursos/estadisticas/inscriptosACurso/<int:pk>', views.pagEstadisticasInscriptosACurso, name='incriptosACurso'),
    path('administracionDeCursos/estadisticas/pagosDelCurso/<int:pk>', views.pagEstadisticasPagoCurso, name='pagosDelCurso'),

    path('administracionDeCursos/estadisticas/inscriptosALosCursos', views.pagEstadisticasInscriptosACursos, name='incriptosALosCursos'),
    path('administracionDeCursos/estadisticas/inscriptosALosCursosFiltrados', views.pagEstadisticasInscriptosACursoFiltrados, name='incriptosALosCursosFiltrados'),

    path('administracionDeCursos/estadisticas/pagosEnCursos', views.pagEstadisticasPagoCursos, name='pagosEnCursos'),
    path('administracionDeCursos/estadisticas/pagosEnCursosFiltrados', views.pagEstadisticasPagoCursosFiltrados, name='pagosEnCursosFiltrados'),

    path('create/', views.nuevoCurso, name='nuevoCurso'),
    path('create/docentes/<int:pk>', views.escogerExpositores, name='escogerExpositores'),
    path('create/docentes/<int:pk>,<str:pkD>/agregar', views.escogerExpositores2, name='escogerExpositores2'),
    path('create/docentes/<int:pk>,<str:pkD>/quitar', views.quitarExpositores, name='escogerExpositores3'),
    path('edit/<int:pk>', views.curso_edit, name='curso_edit'),
    path('delete/', views.curso_delete, name='curso_delete'),

    path('create_resolucion/<int:pk>/', views.nuevaResolucion, name="create_resolucion"),

]
app_name = 'apps'

gestion_cursos_posgrado/gestion_cursos_posgrado/urls.py
from django.contrib import admin
from django.db.models import Index
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('apps/', include('apps.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base/home.html'), name='home'),
]

gestion_cursos_posgrado/apps/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date

class localidad(models.Model):
    dom_cod_localidad = models.PositiveIntegerField(primary_key=True)
    dom_descrip_localidad = models.CharField(max_length=100)

class provincia(models.Model):
    dom_cod_provincia = models.PositiveIntegerField(primary_key=True)
    dom_descrip_provincia = models.CharField(max_length=60)


class persona(models.Model):
    GENERO_OPCIONES_SEXO = {
        ('M','Masculino'),
        ('F','Femenino'),
    }
    GENERO_OPCIONES_ESTADOCIVIL={
        ('SOLTERO','Soltero'),
        ('CASADO','Casado'),
        ('VIUDO','Viudo'),
        ('DIVORCIADO','Divorciado'),
    }
    cuit_persona= models.CharField(max_length=11,primary_key=True)
    apellido = models.CharField(max_length=50,null=True)
    nombre=models.CharField(max_length=50, null=True)
    sexo_persona = models.CharField(max_length=1,choices=GENERO_OPCIONES_SEXO, null=True)
    fecha_nac_persona = models.DateField(null=True)
    estado_civil = models.CharField(max_length=10,choices=GENERO_OPCIONES_ESTADOCIVIL, null=True)
    dom_calle = models.CharField(max_length=40,blank=True, null=True)
    dom_nro_calle = models.PositiveIntegerField(blank=True,null=True)
    departamento = models.CharField(max_length=100,blank=True,null=True)
    correo_electronico = models.CharField(max_length=100, blank=True, null=True)
    telefono = models.BigIntegerField(blank=True, null=True)
    dom_cod_localidad = models.ForeignKey(localidad, on_delete=models.PROTECT, null=True)
    dom_cod_provincia = models.ForeignKey(provincia, on_delete=models.CASCADE, null=True)

    User = models.OneToOneField(
        User,null=True,on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_related",
        related_query_name="%(app_label)s_%(class)ss",
    )

    # User = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="content_%(class)s")
    def __str__(self):
        return self.nombre


class curso(models.Model):
    GENERO_OPCIONES_MODALIDAD = {
        ('VIRTUAL', 'Virtual'),
        ('PRESENCIAL','Presencial'),
        ('MIXTA','Mixta'),
    }
    GENERO_OPCIONES_ESTADO = {
        ('A', 'Aprobado'),
        ('P', 'Pendiente'),
        ('D', 'Desaprobado'),
    }
    cod_curso = models.AutoField(primary_key=True)
    nombre_curso = models.CharField(max_length=200, null=True)
    fecha_proposicion = models.DateField(default=date.today)
    objetivo_general = models.CharField(max_length=200, null=True)
    modalidad_curso = models.CharField(max_length=50,choices=GENERO_OPCIONES_MODALIDAD,null=True)
    horario_curso = models.PositiveIntegerField(null=True)
    duracion_curso = models.PositiveIntegerField(null=True)
    fecha_ini_curso = models.DateField(null=True)
    fecha_fin_curso = models.DateField(null=True)
    cant_minima_alumnos = models.PositiveIntegerField(null=True)
    cant_maxima_alumnos = models.PositiveIntegerField(null=True)
    costo_curso = models.PositiveIntegerField(null=True)
    estado_curso = models.CharField(max_length=1,choices=GENERO_OPCIONES_ESTADO, default='P')
    expositores = models.ManyToManyField('docente', related_name='expositores', db_table='expositores')

    def __str__(self):
        return self.nombre_curso


class curso_persona(models.Model):
#<<<<<<< HEAD
    cuit_persona = models.ForeignKey(persona,on_delete=models.CASCADE)  #persona
    cod_curso = models.ForeignKey(curso,on_delete=models.CASCADE)   #curso
    fecha_inscripcion = models.DateField(default=date.today)
    fehca_examen = models.DateField(null=True)
    nota_examen = models.SmallIntegerField(null=True)
    porcentaje_asistencia = models.SmallIntegerField(null=True)
    nro_registro = models.AutoField(primary_key=True)
    #nro_intentos = models.SmallIntegerField(primary_key=True)
    estado_de_pago = models.BooleanField(default=False)
"""
=======
    cuit_persona = models.ForeignKey(persona,on_delete=models.CASCADE)
    cod_curso = models.ForeignKey(curso,on_delete=models.CASCADE)
    fecha_inscripcion = models.DateField(default=date.today)
    fehca_examen = models.DateField(null=True,blank=True)
    nota_examen = models.SmallIntegerField(null=True,blank=True)
    porcentaje_asistencia = models.SmallIntegerField(null=True,blank=True)
    nro_registro = models.AutoField(primary_key=True)


>>>>>>> 09aa07856dab98ae8a5a7bf09613b30f3a9463b5 """

# **** RELACION-UNO A UNO- (OneToOneField) ****
class docente(models.Model):
    cuit_persona = models.OneToOneField(persona, on_delete=models.CASCADE, primary_key=True)
    curriculum = models.FileField(null=True, blank=True)
    fecha_ingreso = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.fecha_ingreso


class alumno(models.Model):
    cuit_persona = models.OneToOneField(persona, on_delete=models.CASCADE)
    matricula_univ = models.AutoField(primary_key=True)

    def __str__(self):
        return self.matricula_univ


# class forma_pago(models.Model):
#     cod_forma_pago = models.AutoField(primary_key=True)
#     descrip_forma_pago = models.CharField(max_length=100)




class pago(models.Model):
    cuit_persona = models.OneToOneField(persona,on_delete=models.CASCADE)
    cod_curso = models.ForeignKey(curso,on_delete=models.CASCADE)
    fecha_pago = models.DateField(default=date.today)
    importe_pago = models.PositiveIntegerField(null=True)
    forma_pago = models.CharField(max_length=30, null=True)
    nro_recibo = models.AutoField(primary_key=True)



class universidad(models.Model):
    cod_universidad = models.PositiveIntegerField(primary_key=True)
    nombre_universidad = models.CharField(max_length=60)
    web = models.CharField(max_length=60)


class tipo_titulo(models.Model):
    cod_tipo_titulo = models.PositiveIntegerField(primary_key=True)
    des_tipo_titulo = models.CharField(max_length=30)


class titulo(models.Model):
    cod_titulo = models.PositiveIntegerField(primary_key=True)
    nombre_titulo = models.CharField(max_length=60)
    cod_universidad = models.ForeignKey('universidad', on_delete=models.PROTECT)
    cod_tipo_titulo = models.ForeignKey('tipo_titulo', on_delete=models.PROTECT)


class persona_titulo(models.Model):
    cod_titulo = models.ForeignKey('titulo', on_delete=models.PROTECT)
    cuil_persona = models.ForeignKey('persona', on_delete=models.PROTECT)
    fecha_titulo = models.DateField(null=True)

"""
class propuesta_curso(models.Model):
    cod_curso = models.OneToOneField('curso', on_delete=models.PROTECT, related_name='propuesta')
    cuil_persona = models.ForeignKey('persona', on_delete=models.PROTECT)
    fecha_propuesta_curso = models.DateField(null=True)
"""

class resolucion(models.Model):
    cod_curso = models.OneToOneField('curso', on_delete=models.PROTECT, related_name='resolucion')
    nro_resolucion = models.AutoField(primary_key=True)
    fecha_resolucion = models.DateField(default=date.today)

    def __str__(self):
        return "Resolucion {}".format(self.nro_resolucion)

class semana_curso(models.Model):
    cod_curso = models.ForeignKey('curso', on_delete=models.CASCADE, related_name='semanas')
    nro_semana = models.PositiveIntegerField(primary_key=True)
    objetivo_semanal = models.CharField(max_length=100, null=True)
    contenido_semanal = models.CharField(max_length=100, null=True)

gestion_cursos_posgrado/apps/templates/admin-cursos/pag-admin.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Administración de cursos{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/estilosIniciales.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/inicio.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/estilo_inicio_sesion.css' %}">
{% endblock %}

{% block header %}

    <div id="imagenCabecera" class="card text-white">
      <!--<img src="../images/logotipo.png" class="card-img opacity-75  w-50 rounded mx-auto d-block " alt="imagenDeFondo"> -->
        <img src="{% static 'img/logotipo.png' %}" class="card-img opacity-75  w-50 rounded mx-auto d-block " alt="imagenDeFondo">
    </div>

{% endblock %}

{% block contenido %}

        <section class="p-2">

			<div class="card col-md-6 p-3">
				<div class="card-header abs-center bg-info">
					<h2>¿Qué desea hacer?</h2>
				</div>
				<div class="card-body p-0 py-1">
					<div class="col-md-12 bg-secondary">
						<a href="../create/" class="text-white">Crear un curso</a>
					</div>
					<div class="col-md-12 bg-info">
						<a href="./cursosDisponibles" class="text-white">Estados de los cursos</a>
					</div>
					<div class="col-md-12 bg-secondary">
						<a href="./estadisticas" class="text-white">Gestión de estadisticas</a>
					</div>
				<!--	<nav class="navbar bg-light">
						<ul class="navbar-nav">
							<li class="nav-item"><a href="./pag-crear-curso.html">Crear un curso</a></li>
							<li class="nav-item"><a href="#">Estados de los cursos</a></li>
							<li class="nav-item"><a href="./pag-estadistica.html">Listado de inscripciones</a></li>
						</ul>
					</nav>  -->
				</div>
			<!-- <div class="card-footer">Footer</div> -->
			</div>
        </section>
{% endblock %}

gestion_cursos_posgrado/apps/templates/admin-cursos/pag-agregar-docentes-curso.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Agregar docentes a curso{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/inicio.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/tabla.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/estilosIniciales.css' %}">
{% endblock %}

{% block header%}
<header>
    <div id="imagenCabecera" class="card text-white">
        <img src="{% static 'img/logotipo.png' %}" class="card-img opacity-75  w-50 rounded mx-auto d-block " alt="imagenDeFondo">
    </div>
</header>
{% endblock %}

{% block contenido %}

  {% if messages %}
      {% for message in messages %}
			{% if message.tags == 'error' %}  <div class="message mt-1 mb-2 text-center bg-warning">{{ message }}</div>{% endif %}
			{% if message.tags == 'success' %}  <div class="message mt-1 mb-2 text-center bg-success">{{ message }}</div>{% endif %}
      {% endfor %}
  {% endif %}

<h2>Expositores del curso {{cursoC.cod_curso}}: {{cursoC.nombre_curso}}</h2>

<div class="card bg-info p-3" id="carta_p" name="carta_p">
	<div class="card-header abs-center bg-white"><b>DOCENTES REGISTRADOS</b></div>
		<div class="card-body bg-light">
			<div class="table-wrapper table-hover">
				<table class="table t2" id="tabla_profesores">
					<thead>
						<tr>
							<th>Apellido/s</th>
							<th>Nombre/s</th>
							<th>CUIL</th>
							<th>ACCIÓN</th>
						</tr>
					</thead>
					<tbody id="cuerpo_tabla_profe">
						{% for docente in docentes.all %}
						<tr>
							<td>{{docente.cuit_persona.apellido}}</td>
							<td>{{docente.cuit_persona.nombre}}</td>
							<td>{{docente.cuit_persona.cuit_persona}}</td>
							<td>
								<div class="col-md-4">
									<button type="button"><a href="{% url 'apps:escogerExpositores2' cursoC.cod_curso docente.cuit_persona.cuit_persona %}">AGREGAR</a></button>
								</div>
							</td>
						</tr>
						{% endfor %}
					</tbody>

				</table>
			</div>
		</div>
</div>



<h2>EXPOSITORES ESCOGIDOS</h2>
<table class="table" >
					<thead>
						<tr>
							<th>Apellido/s</th>
							<th>Nombre/s</th>
							<th>CUIL</th>
							<th>ACCIÓN</th>
						</tr>
					</thead>
					<tbody class="">
						{% for expositor in expositores %}
						<tr>
							<td>{{expositor.cuit_persona.apellido}}</td>
							<td>{{expositor.cuit_persona.nombre}}</td>
							<td>{{expositor.cuit_persona.cuit_persona}}</td>
							<td>
								<div class="col-md-4">
									<button type="button"><a href="{% url 'apps:escogerExpositores3' cursoC.cod_curso expositor.cuit_persona.cuit_persona %}">QUITAR</a></button>
								</div>
							</td>
						</tr>
						{% endfor %}
					</tbody>

				</table>

{% endblock %}

gestion_cursos_posgrado/apps/templates/admin-cursos/pag-crear-curso.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Creación de curso{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/inicio.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/tabla.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/estilosIniciales.css' %}">
{% endblock %}

{% block header%}
<header>
    <div id="imagenCabecera" class="card text-white">
        <img src="{% static 'img/logotipo.png' %}" class="card-img opacity-75  w-50 rounded mx-auto d-block " alt="imagenDeFondo">
    </div>
</header>
{% endblock %}

{% block contenido %}
<h1 class="card-title text-center text-dark">PROPOSICIÓN DE CURSOS</h1>
<div class="container p-4 mt-5 border">

			<h2>Complete la siguiente información</h2>
			<form class="form" method="post" id="formulario" onsubmit="return validador();">
				<div class="row">
					<div class="w-100"></div>
					<label class=" mr-sm-2"><b class="titulo-grupo">Datos indispensables</b></label>
					<div class="w-100"></div>

					<div class="col-md-12">
						<div class="form-floating mb-3 mr-sm-2  ml-sm-2">
							<input type="text" id="nombre_c" name="nombre_curso" class="form-control" required>
							<label for="nombre_c">Nombre:</label>
						</div>
					</div>
				</div>

				<div class="row">

					<label class="mr-sm-2"><b class="titulo-grupo">Fechas</b></label>
					<div class="w-100"></div>

					<div class="col-md-6">
						<div class="form-floating mb-3">
							<input type="date" id="fecha_inic" name="fecha_ini_curso" class="form-control" required>
							<label for="fecha_inic">Inicio del curso:</label>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-floating mb-3">
							<input type="date" id="fecha_fin" name="fecha_fin_curso" class="form-control" required>
							<label for="fecha_fin">Fin del curso:</label>
						</div>
					</div>
				</div>

				<div class="row">
					<label class="mr-sm-2"><b class="titulo-grupo">Información de la cursada</b></label>
					<div class="w-100"></div>

					<div class="col-12">
						<label for="objetivo_c" class="mr-sm-2">Objetivo general del curso:</label>
						<textarea id="objetivo_c" name="objetivo_general" class="form-control mb-2 mr-sm-4" rows="2"></textarea>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label for="modalidad_c" class="mr-sm-2">Modalidad:</label>

							<select class="form-control mb-2 mr-sm-4" id="modalidad_c" name="modalidad_curso" required>
									<option value="VIRTUAL">Virtual</option>
									<option value="PRESENCIAL">Presencial</option>
									<option value="MIXTA">Mixta</option>
							</select>

						</div>

					</div>
					<div class="col-md-4">
						<label for="duracion_c" class="mr-sm-2">Duracion:</label>
						<div class="input-group mb-3">
						  <input type="number" class="form-control" id="duracion_c" name="duracion_curso" aria-label="Recipient's username" aria-describedby="basic-addon2">
						  <span class="input-group-text" id="basic-addon2">hs</span>
						</div>

					</div>

					<!-- probar input de tipo texto y hacer parseFloat() -->
					<div class="col-md-4">
						<label for="costo_c" class="mr-sm-2">Costo:</label>
						<input type="text" id="costo_c" name="costo_curso" class="form-control" onkeypress="return ingresarFloat(event);">
					</div>


				<!-- Cantidades máximas y minimas-->
				<div class="row">
					<label class="mr-sm-2"><b class="titulo-grupo">Cantidad de alumnos</b></label>
					<div class="w-100"></div>
					<div class="col-md-6">
						<div class="form-floating mb-3">
							<input type="number" id="cant_min_a" name="cant_minima_alumnos" class="form-control">
							<label for="cant_min_a">Minima:</label>
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-floating mb-3">
							<input type="number" id="cant_max_a" name="cant_maxima_alumnos" class="form-control">
							<label for="cant_max_a">Máxima:</label>
						</div>
					</div>
				</div>

				<div class="row">

						<div class="col-6 abs-center">
							<button class="btn btn-success mb-2 mr-sm-4" type="submit">Confirmar</button>
							<!-- <button class="btn btn-success mb-2 mr-sm-4" type="submit" onclick="return validador();">Confirmar</button> -->
						</div>

						<div class="col-6 abs-center">
							<button class="btn btn-dark mb-2 mr-sm-4" type="reset" id="b_cancelar">Cancelar</button>
						</div>

					</div>
				</div>
				{% csrf_token %}
			</form>
</div>

<script src="{% static 'scripts/validador_de_curso.js' %}"></script>
<script src="{% static 'scripts/tecleo_valido_input.js' %}"></script>
{% endblock %}

gestion_cursos_posgrado/apps/templates/admin-cursos/pag-estadistica1.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Inscriptos al curso{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/inicio.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/estilo_inicio_sesion.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/tabla.css' %}">
{% endblock %}

{% block header %}
<header>
    <div id="imagenCabecera" class="card text-white">
        <img src="{% static 'img/logotipo.png' %}" class="card-img opacity-75  w-50 rounded mx-auto d-block " alt="imagenDeFondo">
    </div>
</header>
{% endblock %}

{% block contenido %}
<h1>Curso {{cursoE.cod_curso}}: {{cursoE.nombre_curso}}</h1>
<h3>Alumnos inscriptos</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>APELLIDO</th>
      <th>NOMBRE</th>
      <th>CUIL</th>
      <th>PAGO</th>
    </tr>
  </thead>
  <tbody>
    {% for curso in cursoInscripto.all %}
        <tr>
          <td>{{curso.cuit_persona.apellido}}</td>
          <td>{{curso.cuit_persona.nombre}}</td>
          <td>{{curso.cuit_persona.apellido}}</td>
          {% if curso.estado_de_pago == False %}
            <td>Aún no</td>
          {% else %}
            <td>Pagado</td>
          {% endif %}
        </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

gestion_cursos_posgrado/apps/templates/admin-cursos/pag-tabla.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Cursos registrados{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/estilosIniciales.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/inicio.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/tabla.css' %}">
{% endblock %}

{% block header%}

    <div id="imagenCabecera" class="card text-white">
        <img src="{% static 'img/logotipo.png' %}" class="card-img opacity-75  w-50 rounded mx-auto d-block " alt="imagenDeFondo">
    </div>

{% endblock %}

{% block contenido %}
		<!--- --- --- --- --->
		{% if messages %}
      	{% for message in messages %}
			{% if message.tags == 'error' %}  <div class="message mt-1 mb-2 text-center bg-warning">{{ message }}</div>{% endif %}
			{% if message.tags == 'success' %}  <div class="message mt-1 mb-2 text-center bg-success">{{ message }}</div>{% endif %}
      {% endfor %}
  {% endif %}

		<h3 class="texto_centro">En está tabla se encuentran todos los cursos que han sido registrados, aprobados o desaprobados</h3>
		<div class="container-fluid p-3">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Codigo</th>
						<th>Nombre</th>
						<th>Estado</th>
						<th>Acción</th>
					</tr>
				</thead>
				<tbody>
					{% for curso in cursos %}
						<tr>
							<td>{{curso.cod_curso}}</td>
							<td>{{curso.nombre_curso}}</td>

							<td>{{curso.estado_curso}}</td>
							<td>
								<form action="{% url 'apps:curso_delete' %}" method="POST">
									{% csrf_token %}
									<div class="row">

										<div class="col-md-4">
										<!--	<input type="hidden" name="id_programa" value="{{ curso.id }}"> -->
											<button type="button" class="editar"><a href="{% url 'apps:curso_edit' curso.cod_curso %}">Editar</a></button>
											<!-- <button type="button" class="editar">Editar</button> -->
										</div>
										<div class="col-md-4">
											<input class="oculto" name="cod_curso" value="{{curso.cod_curso}}">
											<button type="submit" value="Eliminar" class="quitar" onclick="return confirm('¿Está seguro que desea eliminar el registro?');">Eliminar</button>
										</div>
										{% if perms.apps.add_resolucion %}
											<div class="col-md-4">
												<button type="button"><a href="{% url 'apps:create_resolucion' curso.cod_curso %}">Emitir Resolución</a></button>
											</div>
										{% endif %}
									</div>
								</form>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>

		</div>

		<script scr="{% static 'scripts/tablaCursos.js' %}"></script>
{% endblock %}