gestion_cursos_posgrado/apps/urls.py
from django.db.models import Index
from django.urls import path

from apps import views

urlpatterns =[
    path('index/', views.index, name = 'index'),
    path('index/<int:pk>/', views.inscribirPersonsaCurso, name='inscribirPersonsaCurso'),
    path('darDeBajaCursoPersona/<int:pk>', views.darDeBajaPersonsaCurso, name='darDeBajaCursoPersona'),
    path('abonarCurso/<int:pk>/', views.registrarAbonado, name='abonarCurso'),

    path('reciboDePago/<int:pk>,<str:pkC>/',views.reciboDePago, name='reciboDePago'),

    path('index/inicioSesion/', views.inicioSesion, name = 'inicioSesion'),

    path('administracionInscripcion/', views.administracionInscripcion, name='administracionInscripcion'),
    path('index/<int:pk>/nuevaInscripcion/', views.crearPersona, name='nuevaInscripcion'),
    path('editarInscripcion/<int:pk>',views.editarPersona, name='editarInscripcion'),
    path('eliminarInscripcion/<int:pk>',views.borrar_persona, name='eliminarInscripcion'),

    path('registroDocenteAlumno/', views.registroDocenteAlumno, name='registroDocenteAlumno'),

    # path('inscripcion/', views.crearPersona, name='inscripcionAlCurso'),
    # path('inscripcionAlCurso/', views.inscripcionAlCurso, name='inscripcionAlCurso'),
    #path('index/<int:pk>/inscripcionAlCurso', views.inscripcionAlCurso, name='inscripcionAlCurso'),

    path('administracionDeCursos/', views.paginaDelAdmin, name='administracionDeCursos'),
    #path('administracionDeCursos/creacionDeCurso', views.creacionDeCursos, name='creacionDeCurso'),
    path('administracionDeCursos/cursosDisponibles', views.cursosRegistrados, name='cursosDisponibles'),
    #path('administracionDeCursos/resolucion', views.nuevaResolucion, name='resolucion'),

    path('administracionDeCursos/estadisticas', views.pagEstadisticas, name='estadisticas'),
    path('administracionDeCursos/estadisticas/estadisticasFiltradas', views.pagEstadisticasFiltradas, name='estadisticasFiltradas'),

    path('administracionDeCursos/estadisticas/inscriptosACurso/<int:pk>', views.pagEstadisticasInscriptosACurso, name='incriptosACurso'),
    path('administracionDeCursos/estadisticas/pagosDelCurso/<int:pk>', views.pagEstadisticasPagoCurso, name='pagosDelCurso'),

    path('administracionDeCursos/estadisticas/inscriptosALosCursos', views.pagEstadisticasInscriptosACursos, name='incriptosALosCursos'),
    path('administracionDeCursos/estadisticas/inscriptosALosCursosFiltrados', views.pagEstadisticasInscriptosACursoFiltrados, name='incriptosALosCursosFiltrados'),

    path('administracionDeCursos/estadisticas/pagosEnCursos', views.pagEstadisticasPagoCursos, name='pagosEnCursos'),
    path('administracionDeCursos/estadisticas/pagosEnCursosFiltrados', views.pagEstadisticasPagoCursosFiltrados, name='pagosEnCursosFiltrados'),

    path('create/', views.nuevoCurso, name='nuevoCurso'),
    path('create/docentes/<int:pk>', views.escogerExpositores, name='escogerExpositores'),
    path('create/docentes/<int:pk>,<str:pkD>/agregar', views.escogerExpositores2, name='escogerExpositores2'),
    path('create/docentes/<int:pk>,<str:pkD>/quitar', views.quitarExpositores, name='escogerExpositores3'),
    path('edit/<int:pk>', views.curso_edit, name='curso_edit'),
    path('delete/', views.curso_delete, name='curso_delete'),

    path('create_resolucion/<int:pk>/', views.nuevaResolucion, name="create_resolucion"),

]
app_name = 'apps'

gestion_cursos_posgrado/gestion_cursos_posgrado/urls.py
from django.contrib import admin
from django.db.models import Index
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('apps/', include('apps.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base/home.html'), name='home'),
]

gestion_cursos_posgrado/apps/templates/inform-pago-cursos/InscripcionAlCurso.html
{% extends "base/base.html" %}
{% load static %}
{% block title %} Inscripción {% endblock %}



{% block head %}
<link rel="stylesheet" href="{% static 'css/estilosIniciales.css' %}">
<link rel="stylesheet" href="{% static 'css/notificacion.css' %}">
{% endblock %}



{% block ContenidoScript %}
<script src="{% static 'scripts/motrar_ocultar_datos_form.js' %}"></script>
<script src="{% static 'scripts/tecleo_valido_input.js' %}"></script>
{% endblock %}

{% block header %}
<header>
    <div id="imagenCabecera" class="card text-white">
        <img src="{% static 'img/imegenDeFondo.jpg' %}" class="card-img opacity-25" height="350" alt="imagenDeFondo">
        <div class="card-img-overlay">
        <br>
        <h1 class="card-title text-center"><strong> Formulario de Inscripción</strong></h1>
        <br>
        <p class="card-text text-center fst-italic ">Se solicita una secuencia de datos para registrar a la persona.</p>
        </div>
    </div>
</header>
{% endblock %}


{% block contenido %}

<section>
    <br>
    {% if messages %}
        <br>
        <fieldset id = "avisoABM" class= "ms-3 me-3 border border-1 border-primary">
            <br>
            {% for message in messages %}
                {% if message.tags == 'success' %}  <div class="message text-center" role="status"> <strong>{{ message }}</strong></div>{% endif %}
                {% if message.tags == 'get_messages' %} <div class="message text-center" role="status"> <strong>{{ message }}</strong></div>{% endif %}
                {% if message.tags == 'error' %}  <div class="errors text-center" role="alert"><strong>{{ message }}</strong></div>{% endif %}
            {% endfor %}
            <br>
        </fieldset>
        <br>
        <p class="ms-3"><strong> Si quiere registrarse como docente debe de hacer click en el siguiente boton.</strong></p>
        <input type="button" class= "btn btn-outline-primary ms-3" value = "Registrar" onclick="location.href='{% url 'apps:registroDocenteAlumno' %}'">
        <input type="button" class= "btn btn-outline-primary ms-3" value = "No soy docente" onclick="location.href='{% url 'apps:index' %}'">
        <br>
   {% endif %}
    <br>
    <h2 class = "ms-3">Complete los siguientes datos:</h2> <br>

        <form class="needs-validation" novalidate method="post">
<!--    <form class="needs-validation" novalidate action="" method="POST" enctype="multipart/form-data">-->
        <fieldset class= "row gx-2 gy-2  ms-3 me-3 border border-2 border-secondary">
            <legend>Datos de la persona</legend>

            <div class="col-md-4">
                <label for="cuil" class="form-label">Cuil:</label>
                <input type="text" class="form-control" id="cuil" name="cuit_persona" placeholder="40654321" onkeypress="return ingresarCuil(event);" required>
            </div>

            <div class="col-md-4">
                <label for="nombres" class="form-label">Nombre/s:</label>
                <input type="text" class="form-control" id="nombres" name="nombre" placeholder="Pedro" onkeypress="return ingresarSoloLetras(event);" required>
            </div>

            <div class="col-md-4">
                <label for="apellidos" class="form-label">Apellido/s:</label>
                <input type="text" class="form-control" id="apellidos" name="apellido" placeholder="Paez" onkeypress="return ingresarSoloLetras(event);" required>
            </div>

            <div class="col-md-4">
                <label for="tipoSexo" class="form-label">Sexo:</label>
                <select class="form-select" id="tipoSexo" name="sexo_persona" required>
                  <option selected disabled value="">Seleccione</option>
                  <option value="M" >Masculino</option>
                  <option value="F">Femenino</option>
                </select>
                <div class="invalid-feedback">
                    * Oligatorio
                </div>
              </div>

              <div class="col-md-4">
                <label for="fechaNacimiento" class="form-label">Fecha de nacimiento:</label>
                <input type="date" class="form-control" id="fechaNacimiento" name="fecha_nac_persona" required>
            </div>

            <div class="col-md-4">
                <label for="estadoCivil" class="form-label">Estado civil:</label>
                <select class="form-select" id="estadoCivil"  name="estado_civil" required>
                  <option selected disabled value="">Seleccione</option>
                  <option value="SOLTERO" >Soltero</option>
                  <option value="CASADO">Casado</option>
                  <option value="VIUDO">Viudo</option>
                  <option value="DIVORCIADO">Divorciado</option>
                </select>
                <div class="invalid-feedback">
                    * Oligatorio
                </div>
              </div>
              <div><br></div>
        </fieldset>

        <br>

        <fieldset  class= "row gx-2 gy-2  ms-3 me-3 border border-2 border-secondary">
            <legend>Domicilio</legend>

            <div class="col-md-10">
                <label for="calle" class="form-label">Calle:</label>
                <input type="text" class="form-control" id="calle" placeholder="Av. Maximo Victoria" name="dom_calle" required>
            </div>

            <div class="col-md-2">
                <label for="numeroCasa" class="form-label">Número:</label>
                <input type="text" class="form-control" id="numeroCasa" name="dom_nro_calle" placeholder="604" onkeypress="return ingresarSoloNumeros(event);" required>
            </div>

            <div class="col-md-4">
                <label for="localidad" class="form-label">Localidad:</label>
                <select class="form-select" id="localidad"  name="dom_cod_localidad" required>
                  <option selected disabled value="">Seleccione</option>
                    {% for localidad in localidad.all %}
                        <option value="{{localidad.dom_cod_localidad}}" >{{localidad.dom_descrip_localidad}}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback">
                    * Oligatorio
                </div>
<!--                <input type="text" class="form-control" id="localidad" name="dom_cod_localidad" placeholder="San Fernando del Valle de Catamarca" onkeypress="return ingresarSoloLetras(event);" required>-->
            </div>
            <div class="col-md-4">
                <label for="departamento" class="form-label">Departamento:</label>
                <input type="text" class="form-control" id="departamento" name="departamento" placeholder="Capital" onkeypress="return ingresarSoloLetras(event);"  required>
            </div>

            <div class="col-md-4">
                <label for="provincia" class="form-label">Provincia:</label>
                <select class="form-select" id="provincia"  name="dom_cod_provincia" required>
                  <option selected disabled value="">Seleccione</option>
                    {% for provincia in provincia.all %}
                        <option value="{{provincia.dom_cod_provincia}}" >{{provincia.dom_descrip_provincia}}</option>
                    {% endfor %}
                </select>
<!--                <input type="text" class="form-control" id="provincia" name="dom_cod_provincia" placeholder="Catamarca" onkeypress="return ingresarSoloLetras(event);" required>-->
            </div>
            <div><br></div>
        </fieldset>

        <br>

        <fieldset  class= "row gx-2 gy-2  ms-3 me-3 border border-2 border-secondary">
            <legend>Datos de contacto</legend>

            <div class="col-md-6">
                <label for="telefonoParticular" class="form-label">Telefono Particular:</label>
                <input type="text" class="form-control" id="telefonoParticular" name="telefono" placeholder="0383 443-5112" >
            </div>
            <div class="col-md-6">
                <label for="correoElectronico" class="form-label">Correo Electronico:</label>
                <input type="Email" class="form-control" id="correoElectronico" name="correo_electronico" placeholder="Ejemplo@gmail.com" >
            </div>

            <div><br></div>
        </fieldset>


<!--        <br>-->
<!--        <label class = "ms-3" for="tipoCategoria"  onclick="OcultarMostrarDatosDelDocente();">Seleccione la categoría:  </label>-->
<!--        <input type="radio" id="tipoCategoria" name="tipoCategoria" value="alumno" checked="checked" onclick="OcultarMostrarDatosDelDocente();"> Alumno &nbsp;&nbsp;-->
<!--        <input type="radio" name="tipoCategoria" value="docente" onclick="OcultarMostrarDatosDelDocente();"> Docente &nbsp;&nbsp;-->

<!--        <br><br>-->

<!--        <fieldset id= "datosDocente" class= "row gx-2 gy-2  ms-3 me-3 border border-2 border-secondary">-->

<!--            <div class="col-md-8">-->
<!--                <label for="fechaInicioAlTrabajo" class="form-label">Fecha de Inicio al trabajo:</label>-->
<!--                <input type="date" class="form-control" id="fechaInicioAlTrabajo" name="fecha_ingreso">-->
<!--            </div>-->
<!--            <div class="col-md-4">-->
<!--                <label for="curriculumVitae" class="form-label">Ingrese un curriculum vitae</label>-->
<!--                <input type="file" class="form-control" id="curriculumVitae" name="curriculum" >-->
<!--            </div>-->
<!--            <div><br></div>-->
<!--        </fieldset>-->
        <br>

        <input type="submit" class= "btn btn-outline-primary ms-3" value = "Guardar" onclick="validarDatos();">
        <input type="reset" class= "btn btn-outline-primary" value = "Cancelar">
<!--        <input type="number"  value="" name="User">-->
            {{form.User}}
        {% csrf_token %}
    </form>
</section>
{% endblock %}

gestion_cursos_posgrado/apps/templates/inform-pago-cursos/darDeBajaCursoPersona.html
{% extends "base/base.html" %}
{% load static %}
{% block title %} Dar de baja {% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/estilosIniciales.css' %}">
{% endblock %}

{% block header %}
<header>
    <div id="imagenCabecera" class="card text-white">
        <img src="{% static 'img/imegenDeFondo.jpg' %}" class="card-img opacity-25" height="350" alt="imagenDeFondo">
        <div class="card-img-overlay">
        <br>
        <h1 class="card-title text-center"><strong>Dar de Baja</strong></h1>
        <br>
        <p class="card-text text-center fst-italic "></p>
        </div>
    </div>
</header>
{% endblock %}


{% block contenido %}

<section>
    <br><br>
    <form method="post" enctype="multipart/form-data">
        <fieldset class= "row gx-2 gy-2  ms-3 me-3 border border-2 border-secondary">
            <h2 class="text-center">¿Esta seguro de "Darse de Baja" en el curso?</h2>
            <p></p>
            <input type="submit" class= "btn btn-outline-danger " value = "Sí, eliminar" >
            <br>
            <input type="button" class= "btn btn-outline-primary"  value = "Cancelar" onclick="location.href='{% url 'apps:index' %}'">
            <p></p>
        </fieldset>
        {% csrf_token %}
    </form>
</section>
{% endblock %}

gestion_cursos_posgrado/apps/templates/inform-pago-cursos/detalleDelCurso.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Detalle{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/estilosIniciales.css' %}">
<link rel="stylesheet" href="{% static 'css/notificacion.css' %}">
{% endblock %}


{% block header %}
<header>
    <div id="imagenCabecera" class="card text-white">
        <!-- <img src="../images/imegenDeFondo.jpg" class="card-img opacity-25" height="350" alt="imagenDeFondo"> -->
        <img src="{% static 'img/imegenDeFondo.jpg' %}" class="card-img opacity-25" height="350" alt="imagenDeFondo">
        <div class="card-img-overlay">
        <br>
        <h1 class="card-title text-center"><strong> Información Detallada del Curso </strong></h1>
        <br>
        <p class="card-text text-center fst-italic ">Se mostrará información sobre los objetivos generales y semanales, además de datos importantes a tener en cuenta para poder inscribirse al curso como ser: las fechas de inicio y de fin, cantidades minimas y maximas de alumnos, modalidad, duración total, y el costo a abonar.</p>
        </div>
    </div>
</header>
{% endblock %}


{% block contenido %}
    <nav id="barraDeNavegacion" class="navbar navbar-expand-md navbar-dark border-3 border-bottom border-primary">
        <div class= "container-fluid">
            <button type = "button" class = "navbar-toggler" data-bs-toggle = "collapse" data-bs-target = "#MenuNavegacion">
                <span class = "navbar-toggler-icon"></span>
            </button>
            <div id = "MenuNavegacion" class= "collapse navbar-collapse">
                <ul class = "navbar-nav ms-3">
                    {% if personaRegistrada < 1 %}
                        <li class="nav-item"><a class= "nav-link" href="{% url 'apps:nuevaInscripcion' curso.cod_curso %}" target="_parent">Registrar datos usuario</a></li>
                    {% endif %}
                    <li><br></li>
                  </ul>
                  <ul class = "navbar-nav ms-3 position-absolute top-50 end-0 translate-middle">
                    {% for persona in persona.all %}
                        {% for curPer in cursoPersona.all %}
                            {% if curPer.cuit_persona_id == persona.cuit_persona %}
                                {% if curPer.cod_curso_id == curso.cod_curso %}
                                    {% if curPer.estado_de_pago == False %}
                                      <li>
                                          <a class = "nav-link text-nowrap" href= "{% url 'apps:abonarCurso' curso.cod_curso %}" target="_parent">Abonar Curso</a>
                                      </li>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                      <li class = "nav-item">
                          {% for persona in persona.all %}
                                <a class = "nav-link text-nowrap" href= "{% url 'apps:editarInscripcion' persona.cuit_persona %}" target="_parent">Datos personales</a>
                          {% endfor %}
                      </li>
                  </ul>
            </div>
        </div>
    </nav>



<section>
<!--    <div class="">-->
<!--        {% for persona in persona.all %}-->
<!--            <button type="button" class="Modificar"><a href="{% url 'apps:editarInscripcion' persona.cuit_persona %}">Datos personales</a></button>-->
<!--        {% endfor %}-->
<!--    </div>-->

    <div class = "container">
        <div class="row justify-content-start">
            <div class="col-8">
                <br>
                <h2>{{curso.nombre_curso}}</h2>
                <p><strong>Objetivos Generales del curso: </strong></p>
                <!-- Información irrelevante para visualizar -->
                <p>{{curso.objetivo_general}}</p>
                <!--<p>(Informacion irrelevante de referencia)At W3Schools you will find complete references about HTML elements, attributes, events, color names, entities, character-sets, URL encoding, language codes, HTTP messages, browser support, and more.</p> -->
                <br>

<!--                <div class="accordion" id="accordionExample">-->
<!--                    <div class="accordion-item">-->
<!--                      <h2 class="accordion-header" id="headingOne">-->
<!--                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">-->
<!--                          Mas Información-->
<!--                        </button>-->
<!--                      </h2>-->
<!--                      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">-->
<!--                        <div class="accordion-body">-->
<!--                            <h3>Obejetivos y Contenidos de la semana N° {{semana.nro_semana}}</h3>-->
<!--                            <p><strong>Objetivos de la semana: </strong></p>-->
<!--                            <p>{{semana.objetivo_semanal}}</p>-->
<!--                            <p><strong>Contenidos Asociados:</strong></p>-->
<!--                            <p>{{semana.contenido_semanal}}</p>-->
<!--                            &lt;!&ndash;<ul>-->
<!--                                <li>HTML</li>-->
<!--                                <li>CSS</li>-->
<!--                                <li>Tema3</li>-->
<!--                            </ul>&ndash;&gt;-->
<!--                        </div>-->
<!--                      </div>-->
<!--                    </div>-->
<!--                </div>-->
                <br>
            </div>

            <div class="col-4">
                <br>
                <h2>Información Importante</h2>
                <ul>
                    <li><strong>Duración:</strong> {{curso.duracion_curso}}</li>
                    <li><strong>Modalidad:</strong> {{curso.modalidad_curso}} </li>
                    <li><strong> de incio:</strong> {{curso.fecha_ini_curso | date:"d/m/Y" }}</li>
                    <li><strong>Fecha de fin:</strong> {{curso.fecha_fin_curso | date:"d/m/Y" }}</li>
                    <li><strong>Cantidad Maxima de Alumnos:</strong> {{curso.cant_maxima_alumnos}}</li>
                    <li><strong>Cantidad Minima de Alumnos:</strong> {{curso.cant_minima_alumnos}}</li>
                    <li><strong>Costo/Precio:</strong> {{curso.costo_curso}}</li>
                    <li><strong>Estado del Curso:</strong> {% if curso.estado_curso == 'A' %}
                                        APROBADO
                                    {% else %}
                                        {% if cursos.estado_curso == 'P' %}
                                            PENDIENTE
                                        {% else %}
                                            DESAPROBADO
                                        {% endif %}
                                    {% endif %}
                    </li>
                </ul>
                <div>
                    <p> <strong> Nota </strong>:  Si el cumple especificamente con las condiciones de Fecha, Cant. max de alumnos y el Estado del curso podrá inscribirse al curso.</p>
<!--                    <input type="button" class="btn btn-outline-primary" value = "Inscribirse al curso" onclick="location.href='{% url 'apps:nuevaInscripcion' curso.cod_curso %}'">-->


                    <form method="post" enctype="multipart/form-data">
                        {% for persona in persona.all %}
                            <input type="text"  name="cuit_persona" value="{{persona.cuit_persona}}" style="display: none;">
                        {% endfor %}
                        <input type="text"  name="cod_curso" value="{{curso.cod_curso}}"  style="display: none;" >


                        {% if totalInscriptos < curso.cant_maxima_alumnos %}
                            <p><strong>Total de inscriptos hasta el momento:</strong> {{totalInscriptos}}</p>
                            <input type="submit" class="btn btn-outline-primary" value = "Inscribirse al Curso">
                        {% else %}
                            <p style="color:red;">El curso no tiene cupos disponibles.</p>
                        {% endif %}

                        {% csrf_token %}
                    </form>


                    <br><br>
                </div>

                {% for persona in persona.all %}
                    {% for curPer in cursoPersona.all %}
                        {% if curPer.cuit_persona_id == persona.cuit_persona %}
                            {% if curPer.cod_curso_id == curso.cod_curso %}
                                <div>
                                        <fieldset id = "avisoInscripcion" class= "row border border-1 border-primary">
                                            <p class="my-0"><strong>Nombre y Apellido:</strong>  {{persona.nombre}} {{persona.apellido}} </p>
                                            <p class="my-0"><strong>fecha que se inscribió:</strong>  {{curPer.fecha_inscripcion}} </p>
                                            <div class="d-grid gap-0 d-md-flex justify-content-md-end">
                                                <input type="button" class="btn btn-outline-danger btn-sm  my-2" value = "Dar de baja" onclick="location.href='{% url 'apps:darDeBajaCursoPersona' curPer.nro_registro %}'">
                                                <br>
                                            </div>
                                        </fieldset>
                                </div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </div>
          </div>
    </div>
</section>
{% endblock %}

gestion_cursos_posgrado/apps/templates/inform-pago-cursos/index.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Gestión de Cursos de Posgrado{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/estilosIniciales.css' %}">
<link rel="stylesheet" href="{% static 'css/notificacion.css' %}">
{% endblock %}

{% block header%}
<header>
    <div id="imagenCabecera" class="card text-white">
      <!--<img src="../images/logotipo.png" class="card-img opacity-75  w-50 rounded mx-auto d-block " alt="imagenDeFondo"> -->
        <img src="{% static 'img/logotipo.png' %}" class="card-img opacity-75  w-50 rounded mx-auto d-block " alt="imagenDeFondo">
    </div>
</header>
{% endblock %}


{% block contenido %}
<!--    <nav id="barraDeNavegacion" class="navbar navbar-expand-md navbar-dark border-3 border-bottom border-primary">-->
<!--        <div class= "container-fluid">-->
<!--            <button type = "button" class = "navbar-toggler" data-bs-toggle = "collapse" data-bs-target = "#MenuNavegacion">-->
<!--                <span class = "navbar-toggler-icon"></span>-->
<!--            </button>-->
<!--            <div id = "MenuNavegacion" class= "collapse navbar-collapse">-->
<!--                <ul class = "navbar-nav ms-3">-->
<!--                    {% if personaRegistrada < 1 %}-->
<!--                        <li class="nav-item"><a class= "nav-link" href="{% url 'apps:nuevaInscripcion' curso.cod_curso %}" target="_parent">Registrar datos usuario</a></li>-->
<!--                    {% endif %}-->
<!--                    <li><br></li>-->
<!--                  </ul>-->
<!--                  <ul class = "navbar-nav ms-3 position-absolute top-50 end-0 translate-middle">-->
<!--                      <li class = "nav-item">-->
<!--                          {% for persona in persona.all %}-->
<!--                                <a class = "nav-link text-nowrap" href= "{% url 'apps:editarInscripcion' persona.cuit_persona %}" target="_parent">Datos personales</a>-->
<!--                          {% endfor %}-->
<!--                      </li>-->
<!--                  </ul>-->
<!--            </div>-->
<!--        </div>-->
<!--    </nav>-->



<section>
    {% if messages %}
        <br>
        <fieldset id = "avisoABM" class= "ms-3 me-3 border border-1 border-primary">
            <br>
            {% for message in messages %}
                {% if message.tags == 'success' %}  <div class="message text-center" role="status"> <strong>{{ message }}</strong></div>{% endif %}
                {% if message.tags == 'get_messages' %} <div class="message text-center" role="status"> <strong>{{ message }}</strong></div>{% endif %}
                {% if message.tags == 'error' %}  <div class="errors text-center" role="alert"><strong>{{ message }}</strong></div>{% endif %}
            {% endfor %}
            <br>
        </fieldset>
    {% endif %}

    <div>
        <br>
        <h2 class= "ms-2">Cursos Disponibles:</h2>
<!--        <form class="d-flex">-->
<!--          <input class="form-control me-2 ms-2" type="search" placeholder="Buscar Curso" aria-label="Search">-->
<!--          <button id = "btnBuscar" class="btn btn-outline-primary me-2" type="submit" onclick="cargarNav();">Buscar</button>-->
<!--        </form>-->

        <br>
    </div>
    <div>
        {% for cursos in curso.all %}
            {% if cursos.estado_curso == 'A' %}
            <fieldset class = "ms-3 me-3 border border-2 border-secondary">

                    <h3>{{cursos.nombre_curso}}</h3>
                    <ul>
                        <li>Estado del curso: {% if cursos.estado_curso == 'A' %}
                                                APROBADO
                                            {% else %}
                                                {% if cursos.estado_curso == 'P' %}
                                                    PENDIENTE
                                                {% else %}
                                                    DESAPROBADO
                                                {% endif %}
                                            {% endif %}
                        </li>
                        <li>Fecha de inicio: {{cursos.fecha_ini_curso | date:"d/m/Y" }} </li>
                        <li>Fecha de fin: {{cursos.fecha_fin_curso | date:"d/m/Y" | default_if_none:"SIN DEFINIR" }}</li>
                        <li>Modalidad: {{cursos.modalidad_curso}}</li>
                        <li>Costo del curso: ${{cursos.costo_curso}}</li>
                    </ul>
                    {% if user.is_authenticated %}
                    <a href="{% url 'apps:inscribirPersonsaCurso' cursos.cod_curso %}">Ver Información Detallada</a>
                    {% endif %}
                    <br>
            </fieldset>
            <br>
            {% endif %}
        {% endfor %}

    </div>
</section>
{% endblock %}