gestion_cursos_posgrado/apps/urls.py
from django.db.models import Index
from django.urls import path

from apps import views

urlpatterns =[
    path('index/', views.index, name = 'index'),
    path('index/<int:pk>/', views.inscribirPersonsaCurso, name='inscribirPersonsaCurso'),
    path('darDeBajaCursoPersona/<int:pk>', views.darDeBajaPersonsaCurso, name='darDeBajaCursoPersona'),
    path('abonarCurso/<int:pk>/', views.registrarAbonado, name='abonarCurso'),

    path('reciboDePago/<int:pk>,<str:pkC>/',views.reciboDePago, name='reciboDePago'),

    path('index/inicioSesion/', views.inicioSesion, name = 'inicioSesion'),

    path('administracionInscripcion/', views.administracionInscripcion, name='administracionInscripcion'),
    path('index/<int:pk>/nuevaInscripcion/', views.crearPersona, name='nuevaInscripcion'),
    path('editarInscripcion/<int:pk>',views.editarPersona, name='editarInscripcion'),
    path('eliminarInscripcion/<int:pk>',views.borrar_persona, name='eliminarInscripcion'),

    path('registroDocenteAlumno/', views.registroDocenteAlumno, name='registroDocenteAlumno'),

    # path('inscripcion/', views.crearPersona, name='inscripcionAlCurso'),
    # path('inscripcionAlCurso/', views.inscripcionAlCurso, name='inscripcionAlCurso'),
    #path('index/<int:pk>/inscripcionAlCurso', views.inscripcionAlCurso, name='inscripcionAlCurso'),

    path('administracionDeCursos/', views.paginaDelAdmin, name='administracionDeCursos'),
    #path('administracionDeCursos/creacionDeCurso', views.creacionDeCursos, name='creacionDeCurso'),
    path('administracionDeCursos/cursosDisponibles', views.cursosRegistrados, name='cursosDisponibles'),
    #path('administracionDeCursos/resolucion', views.nuevaResolucion, name='resolucion'),

    path('administracionDeCursos/estadisticas', views.pagEstadisticas, name='estadisticas'),
    path('administracionDeCursos/estadisticas/estadisticasFiltradas', views.pagEstadisticasFiltradas, name='estadisticasFiltradas'),

    path('administracionDeCursos/estadisticas/inscriptosACurso/<int:pk>', views.pagEstadisticasInscriptosACurso, name='incriptosACurso'),
    path('administracionDeCursos/estadisticas/pagosDelCurso/<int:pk>', views.pagEstadisticasPagoCurso, name='pagosDelCurso'),

    path('administracionDeCursos/estadisticas/inscriptosALosCursos', views.pagEstadisticasInscriptosACursos, name='incriptosALosCursos'),
    path('administracionDeCursos/estadisticas/inscriptosALosCursosFiltrados', views.pagEstadisticasInscriptosACursoFiltrados, name='incriptosALosCursosFiltrados'),

    path('administracionDeCursos/estadisticas/pagosEnCursos', views.pagEstadisticasPagoCursos, name='pagosEnCursos'),
    path('administracionDeCursos/estadisticas/pagosEnCursosFiltrados', views.pagEstadisticasPagoCursosFiltrados, name='pagosEnCursosFiltrados'),

    path('create/', views.nuevoCurso, name='nuevoCurso'),
    path('create/docentes/<int:pk>', views.escogerExpositores, name='escogerExpositores'),
    path('create/docentes/<int:pk>,<str:pkD>/agregar', views.escogerExpositores2, name='escogerExpositores2'),
    path('create/docentes/<int:pk>,<str:pkD>/quitar', views.quitarExpositores, name='escogerExpositores3'),
    path('edit/<int:pk>', views.curso_edit, name='curso_edit'),
    path('delete/', views.curso_delete, name='curso_delete'),

    path('create_resolucion/<int:pk>/', views.nuevaResolucion, name="create_resolucion"),

]
app_name = 'apps'

gestion_cursos_posgrado/gestion_cursos_posgrado/urls.py
from django.contrib import admin
from django.db.models import Index
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('apps/', include('apps.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base/home.html'), name='home'),
]

gestion_cursos_posgrado/apps/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date

class localidad(models.Model):
    dom_cod_localidad = models.PositiveIntegerField(primary_key=True)
    dom_descrip_localidad = models.CharField(max_length=100)

class provincia(models.Model):
    dom_cod_provincia = models.PositiveIntegerField(primary_key=True)
    dom_descrip_provincia = models.CharField(max_length=60)


class persona(models.Model):
    GENERO_OPCIONES_SEXO = {
        ('M','Masculino'),
        ('F','Femenino'),
    }
    GENERO_OPCIONES_ESTADOCIVIL={
        ('SOLTERO','Soltero'),
        ('CASADO','Casado'),
        ('VIUDO','Viudo'),
        ('DIVORCIADO','Divorciado'),
    }
    cuit_persona= models.CharField(max_length=11,primary_key=True)
    apellido = models.CharField(max_length=50,null=True)
    nombre=models.CharField(max_length=50, null=True)
    sexo_persona = models.CharField(max_length=1,choices=GENERO_OPCIONES_SEXO, null=True)
    fecha_nac_persona = models.DateField(null=True)
    estado_civil = models.CharField(max_length=10,choices=GENERO_OPCIONES_ESTADOCIVIL, null=True)
    dom_calle = models.CharField(max_length=40,blank=True, null=True)
    dom_nro_calle = models.PositiveIntegerField(blank=True,null=True)
    departamento = models.CharField(max_length=100,blank=True,null=True)
    correo_electronico = models.CharField(max_length=100, blank=True, null=True)
    telefono = models.BigIntegerField(blank=True, null=True)
    dom_cod_localidad = models.ForeignKey(localidad, on_delete=models.PROTECT, null=True)
    dom_cod_provincia = models.ForeignKey(provincia, on_delete=models.CASCADE, null=True)

    User = models.OneToOneField(
        User,null=True,on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_related",
        related_query_name="%(app_label)s_%(class)ss",
    )

    # User = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="content_%(class)s")
    def __str__(self):
        return self.nombre


class curso(models.Model):
    GENERO_OPCIONES_MODALIDAD = {
        ('VIRTUAL', 'Virtual'),
        ('PRESENCIAL','Presencial'),
        ('MIXTA','Mixta'),
    }
    GENERO_OPCIONES_ESTADO = {
        ('A', 'Aprobado'),
        ('P', 'Pendiente'),
        ('D', 'Desaprobado'),
    }
    cod_curso = models.AutoField(primary_key=True)
    nombre_curso = models.CharField(max_length=200, null=True)
    fecha_proposicion = models.DateField(default=date.today)
    objetivo_general = models.CharField(max_length=200, null=True)
    modalidad_curso = models.CharField(max_length=50,choices=GENERO_OPCIONES_MODALIDAD,null=True)
    horario_curso = models.PositiveIntegerField(null=True)
    duracion_curso = models.PositiveIntegerField(null=True)
    fecha_ini_curso = models.DateField(null=True)
    fecha_fin_curso = models.DateField(null=True)
    cant_minima_alumnos = models.PositiveIntegerField(null=True)
    cant_maxima_alumnos = models.PositiveIntegerField(null=True)
    costo_curso = models.PositiveIntegerField(null=True)
    estado_curso = models.CharField(max_length=1,choices=GENERO_OPCIONES_ESTADO, default='P')
    expositores = models.ManyToManyField('docente', related_name='expositores', db_table='expositores')

    def __str__(self):
        return self.nombre_curso


class curso_persona(models.Model):
#<<<<<<< HEAD
    cuit_persona = models.ForeignKey(persona,on_delete=models.CASCADE)  #persona
    cod_curso = models.ForeignKey(curso,on_delete=models.CASCADE)   #curso
    fecha_inscripcion = models.DateField(default=date.today)
    fehca_examen = models.DateField(null=True)
    nota_examen = models.SmallIntegerField(null=True)
    porcentaje_asistencia = models.SmallIntegerField(null=True)
    nro_registro = models.AutoField(primary_key=True)
    #nro_intentos = models.SmallIntegerField(primary_key=True)
    estado_de_pago = models.BooleanField(default=False)
"""
=======
    cuit_persona = models.ForeignKey(persona,on_delete=models.CASCADE)
    cod_curso = models.ForeignKey(curso,on_delete=models.CASCADE)
    fecha_inscripcion = models.DateField(default=date.today)
    fehca_examen = models.DateField(null=True,blank=True)
    nota_examen = models.SmallIntegerField(null=True,blank=True)
    porcentaje_asistencia = models.SmallIntegerField(null=True,blank=True)
    nro_registro = models.AutoField(primary_key=True)


>>>>>>> 09aa07856dab98ae8a5a7bf09613b30f3a9463b5 """

# **** RELACION-UNO A UNO- (OneToOneField) ****
class docente(models.Model):
    cuit_persona = models.OneToOneField(persona, on_delete=models.CASCADE, primary_key=True)
    curriculum = models.FileField(null=True, blank=True)
    fecha_ingreso = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.fecha_ingreso


class alumno(models.Model):
    cuit_persona = models.OneToOneField(persona, on_delete=models.CASCADE)
    matricula_univ = models.AutoField(primary_key=True)

    def __str__(self):
        return self.matricula_univ


# class forma_pago(models.Model):
#     cod_forma_pago = models.AutoField(primary_key=True)
#     descrip_forma_pago = models.CharField(max_length=100)




class pago(models.Model):
    cuit_persona = models.OneToOneField(persona,on_delete=models.CASCADE)
    cod_curso = models.ForeignKey(curso,on_delete=models.CASCADE)
    fecha_pago = models.DateField(default=date.today)
    importe_pago = models.PositiveIntegerField(null=True)
    forma_pago = models.CharField(max_length=30, null=True)
    nro_recibo = models.AutoField(primary_key=True)



class universidad(models.Model):
    cod_universidad = models.PositiveIntegerField(primary_key=True)
    nombre_universidad = models.CharField(max_length=60)
    web = models.CharField(max_length=60)


class tipo_titulo(models.Model):
    cod_tipo_titulo = models.PositiveIntegerField(primary_key=True)
    des_tipo_titulo = models.CharField(max_length=30)


class titulo(models.Model):
    cod_titulo = models.PositiveIntegerField(primary_key=True)
    nombre_titulo = models.CharField(max_length=60)
    cod_universidad = models.ForeignKey('universidad', on_delete=models.PROTECT)
    cod_tipo_titulo = models.ForeignKey('tipo_titulo', on_delete=models.PROTECT)


class persona_titulo(models.Model):
    cod_titulo = models.ForeignKey('titulo', on_delete=models.PROTECT)
    cuil_persona = models.ForeignKey('persona', on_delete=models.PROTECT)
    fecha_titulo = models.DateField(null=True)

"""
class propuesta_curso(models.Model):
    cod_curso = models.OneToOneField('curso', on_delete=models.PROTECT, related_name='propuesta')
    cuil_persona = models.ForeignKey('persona', on_delete=models.PROTECT)
    fecha_propuesta_curso = models.DateField(null=True)
"""

class resolucion(models.Model):
    cod_curso = models.OneToOneField('curso', on_delete=models.PROTECT, related_name='resolucion')
    nro_resolucion = models.AutoField(primary_key=True)
    fecha_resolucion = models.DateField(default=date.today)

    def __str__(self):
        return "Resolucion {}".format(self.nro_resolucion)

class semana_curso(models.Model):
    cod_curso = models.ForeignKey('curso', on_delete=models.CASCADE, related_name='semanas')
    nro_semana = models.PositiveIntegerField(primary_key=True)
    objetivo_semanal = models.CharField(max_length=100, null=True)
    contenido_semanal = models.CharField(max_length=100, null=True)

gestion_cursos_posgrado/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
    {% block head %} {% endblock %}
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    {% block ContenidoScript %}  {% endblock %}


    {% block header %} {% endblock %}

    <nav id="barraDeNavegacion" class="navbar navbar-expand-md navbar-dark border-3 border-bottom border-primary">
        <div class= "container-fluid">
            <a href="{% url 'home' %}" class= "navbar-brand"><strong>GCP</strong></a>
            <button type = "button" class = "navbar-toggler" data-bs-toggle = "collapse" data-bs-target = "#MenuNavegacion">
                <span class = "navbar-toggler-icon"></span>
            </button>
            <div id = "MenuNavegacion" class= "collapse navbar-collapse">
                <ul class = "navbar-nav ms-5">
                    <li class="nav-item"><a class= "nav-link" href="{% url 'apps:index' %}" target="_parent">Inicio</a></li>
                    {% if perms.apps.change_persona and perms.apps.delete_persona %}
                    <li class="nav-item"><a class= "nav-link" href="{% url 'apps:administracionInscripcion' %}" target="_parent">Gestión de Inscriptos</a></li>
                    {% endif %}

                    {% if perms.apps.add_curso and perms.apps.change_curso and perms.apps.delete_curso %}
                    <li class="nav-item"><a class= "nav-link" href="{% url 'apps:administracionDeCursos' %}" target="_parent">Gestión de cursos</a></li>
                    {% endif %}

                    <li class= "nav-item dropdown">
                        <a class= "nav-link dropdown-toggle" href="#" role = "button" data-bs-toggle="dropdown">Opciones de soporte</a>
                        <ul class= "dropdown-menu">
                            <li><a class = "dropdown-item" href="#">Manuales</a></li>
                            <li><a class = "dropdown-item" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Contacta con nosotros</a></li>
                        </ul>
                    </li>
                  </ul>
                  <ul class = "navbar-nav ms-3 position-absolute top-50 end-0 translate-middle">
                      {% if user.is_authenticated %}
                          <a class = "nav-link text-nowrap my-0" target="_parent">Usuario <strong>'{{ user.username }}'</strong></a>
                          <a class = "nav-link text-nowrap my-0" href="/admin/logout/" target="_parent">Cerrar Sesion</a>
                      {% else %}
                          <li class = "nav-item">
                              <a class = "nav-link text-nowrap" href= "/admin/login/" target="_parent">Iniciar sesión</a>
                          </li>
                      {% endif%}
                  </ul>
            </div>
        </div>
        <!-- DATOS DE CONTACTO DESPLEGABLE -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">Email/s de contacto:</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    sergitula.50@gmail.com <br> franvictor18@gmail.com
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cerrar</button>
                </div>
              </div>
            </div>
          </div>
    </nav>

    {% block contenido %} {% endblock %}

    <footer id= "pieDePagina" class="bd-footer py-5 mt-5">
        <div class="container py-5">
            <div class="row">
            <div class="col-lg-3 mb-3">
                <a class="d-inline-flex align-items-center mb-2 link-light text-decoration-none" aria-label="Bootstrap">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="d-block me-2" viewBox="0 0 118 94" role="img"><title>FTyCA</title></svg>
                <span class="fs-5">Facultad de Tecnologia y Cs. Aplicadas - UNCA</span>
                </a>
                <ul class="list-unstyled small text-muted">
                <li class="mb-2 fst-italic link-light text-center opacity-50">Diseño implementado por los estudiantes de la cátedra de 'Programación III'.</li>
                <!-- <li class="mb-2 fst-italic link-light text-center opacity-50">Emails de contacto: <br> sergitula.50@gmail.com <br> franvictor18@gmail.com </li> -->
                </ul>
            </div>

            <div class="col-6 col-lg-2 offset-lg-2 mb-3 link-light">
                <h5>Dirección</h5>
                <ul class="list-unstyled">
                <li class="m2-2 fst-italic link-light opacity-50">Maximio Victoria 55 C.P. 4700 SFV de Catamarca</li>
                </ul>
            </div>
            <div class="col-6 col-lg-2 mb-3 link-light">
                <h5>Contacto</h5>
                <ul class="list-unstyled">
                <li class="mb-2 fst-italic link-light opacity-50">Correo: saa@tecno.unca.edu.ar</li>
                <li class="mb-2 fst-italic link-light opacity-50">Telefono: <br> (+54) 0383-4435112</li>
                </ul>
            </div>
            <div class="col-6 col-lg-2 mb-3 link-light">
                <h5 id= "prob">Sitios Asociados</h5>
                <ul class="list-unstyled">
                <li class="mb-2 text-muted"><a href="https://tecno.unca.edu.ar/" class="nav-link p-0 fst-italic link-light opacity-50" target="_parent">Facultad de Tecnologia</a></li>
                <li class="mb-2 text-muted"><a href="https://moodle2.tecno.unca.edu.ar/moodle/" class="nav-link p-0 fst-italic link-light opacity-50" target="_parent" >Aula Virtual</a></li>
                <li class="mb-2 text-muted"><a href="https://guarani.unca.edu.ar/acceso/login?ref=https://guarani.unca.edu.ar/examen" class="nav-link p-0 fst-italic link-light opacity-50" target="_parent">Siu-Guaraní</a></li>
                </ul>
            </div>
            </div>
        </div>
    </footer>


</body>
</html>

gestion_cursos_posgrado/templates/base/home.html
{% extends "base/base.html" %}
{% load static %}
{% block title %} FTyCA GCP - Inicio {% endblock %}


{% block head %}
	<link rel="stylesheet" href="{% static 'css/estilosIniciales.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/inicio.css' %}">
{% endblock %}


{% block header %}
	<div class="container p-3 my-3 border bg-white">
<!--		<p class="barra-der"><a href="apps/index/inicioSesion">Iniciar sesión</a></p>-->
		<h1>Bienvenido</h1>
		<!--<p class="contenedor-img"><img class="fondo img-fluid" src="./images/img_presentacion_gcp.png" alt="logo gcp"></p> -->
		<p class="contenedor-img"><img class="fondo img-fluid" src="{% static 'img/img_presentacion_gcp.png' %}" alt="logo gcp"></p>
	</div>
{% endblock %}



{% block contenido %}
		<section> 
			<div class="container-fluid">
				<h2>Navega por los cursos que más te interesen</h2>
				<div class="container p-3 my-3 border bg-white">
					<div class="row align-items-centerp-3 gx-5">  
					
						<div class="col-4 border p-3 gx-5 bg-warning">
						<!--	<div class="container border p-3 gx-5 bg-warning"> -->
							    <p class="texto_centro">Cursos activos</p>
								<p class="texto_centro">
									<!-- <a class="btn btn-outline-danger" href="./inform-pago-cursos/index.html" role="button">Ver</a> -->
									<a class="btn btn-outline-danger" href="apps/index" role="button">Ver</a>
								</p>
							<!--	<p><a href="./inform-pago-cursos/index.html">Cursos activos</a><p> -->
						<!--	</div> -->
						</div>
						
					<!--	<div class="w-100 d-none d-xl-block"></div>  -->
						
						<div class="col-4 border p-3 gx-5 bg-warning">
						<!--	<div class="border p-3 gx-5 bg-warning"> -->
								<p class="texto_centro">Consulta opciones de pago</p>
								<p	class="texto_centro">
									<a class="btn btn-outline-danger" href="#" role="button">Ver</a>
								</p>
						<!--	</div>  -->
						</div>
						<div class="w-100"></div>
					</div> 
					
				</div>
			</div>
		</section>

{% endblock %}